import { defineStore } from "pinia";

export const useStore = defineStore('Store', {
    state: () => ({
        current : {
            "location": {
                "name": "Shiraz",
                "region": "Fars",
                "country": "Iran",
                "lat": 29.6,
                "lon": 52.54,
                "tz_id": "Asia/Tehran",
                "localtime_epoch": 1690488732,
                "localtime": "2023-07-27 23:42"
            },
            "current": {
                "last_updated_epoch": 1690488000,
                "last_updated": "2023-07-27 23:30",
                "temp_c": 30.0,
                "temp_f": 86.0,
                "is_day": 0,
                "condition": {
                    "text": "Clear",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                },
                "wind_mph": 6.9,
                "wind_kph": 11.2,
                "wind_degree": 310,
                "wind_dir": "NW",
                "pressure_mb": 1012.0,
                "pressure_in": 29.88,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 22,
                "cloud": 0,
                "feelslike_c": 27.8,
                "feelslike_f": 82.0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "uv": 1.0,
                "gust_mph": 14.1,
                "gust_kph": 22.7,
                "air_quality": {
                    "co": 212.0,
                    "no2": 1.899999976158142,
                    "o3": 154.5,
                    "so2": 3.5,
                    "pm2_5": 19.899999618530273,
                    "pm10": 45.5,
                    "us-epa-index": 2,
                    "gb-defra-index": 2
                }
            }
        },
        forecast : {
            "location": {
                "name": "Shiraz",
                "region": "Fars",
                "country": "Iran",
                "lat": 29.6,
                "lon": 52.54,
                "tz_id": "Asia/Tehran",
                "localtime_epoch": 1690488203,
                "localtime": "2023-07-27 23:33"
            },
            "current": {
                "last_updated_epoch": 1690488000,
                "last_updated": "2023-07-27 23:30",
                "temp_c": 30.0,
                "temp_f": 86.0,
                "is_day": 0,
                "condition": {
                    "text": "Clear",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                },
                "wind_mph": 6.9,
                "wind_kph": 11.2,
                "wind_degree": 310,
                "wind_dir": "NW",
                "pressure_mb": 1012.0,
                "pressure_in": 29.88,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 22,
                "cloud": 0,
                "feelslike_c": 27.8,
                "feelslike_f": 82.0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "uv": 1.0,
                "gust_mph": 14.1,
                "gust_kph": 22.7
            },
            "forecast": {
                "forecastday": [
                    {
                        "date": "2023-07-27",
                        "date_epoch": 1690416000,
                        "day": {
                            "maxtemp_c": 40.9,
                            "maxtemp_f": 105.6,
                            "mintemp_c": 23.1,
                            "mintemp_f": 73.6,
                            "avgtemp_c": 31.3,
                            "avgtemp_f": 88.3,
                            "maxwind_mph": 21.7,
                            "maxwind_kph": 34.9,
                            "totalprecip_mm": 0.0,
                            "totalprecip_in": 0.0,
                            "totalsnow_cm": 0.0,
                            "avgvis_km": 10.0,
                            "avgvis_miles": 6.0,
                            "avghumidity": 15.0,
                            "daily_will_it_rain": 0,
                            "daily_chance_of_rain": 0,
                            "daily_will_it_snow": 0,
                            "daily_chance_of_snow": 0,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "uv": 8.0
                        },
                        "astro": {
                            "sunrise": "06:16 AM",
                            "sunset": "07:56 PM",
                            "moonrise": "02:46 PM",
                            "moonset": "12:47 AM",
                            "moon_phase": "Waxing Gibbous",
                            "moon_illumination": "61",
                            "is_moon_up": 0,
                            "is_sun_up": 0
                        },
                        "hour": [
                            {
                                "time_epoch": 1690403400,
                                "time": "2023-07-27 00:00",
                                "temp_c": 26.3,
                                "temp_f": 79.3,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 6.5,
                                "wind_kph": 10.4,
                                "wind_degree": 285,
                                "wind_dir": "WNW",
                                "pressure_mb": 1006.0,
                                "pressure_in": 29.7,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 24,
                                "cloud": 9,
                                "feelslike_c": 25.0,
                                "feelslike_f": 77.0,
                                "windchill_c": 26.3,
                                "windchill_f": 79.3,
                                "heatindex_c": 25.0,
                                "heatindex_f": 77.0,
                                "dewpoint_c": 3.9,
                                "dewpoint_f": 39.0,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 11.0,
                                "gust_kph": 17.6,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690407000,
                                "time": "2023-07-27 01:00",
                                "temp_c": 25.0,
                                "temp_f": 77.0,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 6.0,
                                "wind_kph": 9.7,
                                "wind_degree": 286,
                                "wind_dir": "WNW",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.69,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 21,
                                "cloud": 11,
                                "feelslike_c": 23.9,
                                "feelslike_f": 75.0,
                                "windchill_c": 25.0,
                                "windchill_f": 77.0,
                                "heatindex_c": 23.9,
                                "heatindex_f": 75.0,
                                "dewpoint_c": 1.3,
                                "dewpoint_f": 34.3,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 12.5,
                                "gust_kph": 20.2,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690410600,
                                "time": "2023-07-27 02:00",
                                "temp_c": 24.1,
                                "temp_f": 75.4,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 4.9,
                                "wind_kph": 7.9,
                                "wind_degree": 301,
                                "wind_dir": "WNW",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.68,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 20,
                                "cloud": 14,
                                "feelslike_c": 23.2,
                                "feelslike_f": 73.8,
                                "windchill_c": 24.1,
                                "windchill_f": 75.4,
                                "heatindex_c": 23.2,
                                "heatindex_f": 73.8,
                                "dewpoint_c": -0.2,
                                "dewpoint_f": 31.6,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 10.3,
                                "gust_kph": 16.6,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690414200,
                                "time": "2023-07-27 03:00",
                                "temp_c": 23.8,
                                "temp_f": 74.8,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 5.4,
                                "wind_kph": 8.6,
                                "wind_degree": 313,
                                "wind_dir": "NW",
                                "pressure_mb": 1006.0,
                                "pressure_in": 29.69,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 19,
                                "cloud": 15,
                                "feelslike_c": 23.0,
                                "feelslike_f": 73.4,
                                "windchill_c": 23.8,
                                "windchill_f": 74.8,
                                "heatindex_c": 23.0,
                                "heatindex_f": 73.4,
                                "dewpoint_c": -0.9,
                                "dewpoint_f": 30.4,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 11.2,
                                "gust_kph": 18.0,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690417800,
                                "time": "2023-07-27 04:00",
                                "temp_c": 23.1,
                                "temp_f": 73.6,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 5.4,
                                "wind_kph": 8.6,
                                "wind_degree": 303,
                                "wind_dir": "WNW",
                                "pressure_mb": 1006.0,
                                "pressure_in": 29.7,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 19,
                                "cloud": 14,
                                "feelslike_c": 22.6,
                                "feelslike_f": 72.7,
                                "windchill_c": 23.1,
                                "windchill_f": 73.6,
                                "heatindex_c": 22.6,
                                "heatindex_f": 72.7,
                                "dewpoint_c": -1.4,
                                "dewpoint_f": 29.5,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 11.2,
                                "gust_kph": 18.0,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690421400,
                                "time": "2023-07-27 05:00",
                                "temp_c": 23.4,
                                "temp_f": 74.1,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 5.1,
                                "wind_kph": 8.3,
                                "wind_degree": 288,
                                "wind_dir": "WNW",
                                "pressure_mb": 1006.0,
                                "pressure_in": 29.71,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 19,
                                "cloud": 12,
                                "feelslike_c": 22.8,
                                "feelslike_f": 73.0,
                                "windchill_c": 23.4,
                                "windchill_f": 74.1,
                                "heatindex_c": 22.8,
                                "heatindex_f": 73.0,
                                "dewpoint_c": -1.2,
                                "dewpoint_f": 29.8,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 10.7,
                                "gust_kph": 17.3,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690425000,
                                "time": "2023-07-27 06:00",
                                "temp_c": 27.3,
                                "temp_f": 81.1,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 2.2,
                                "wind_kph": 3.6,
                                "wind_degree": 265,
                                "wind_dir": "W",
                                "pressure_mb": 1007.0,
                                "pressure_in": 29.72,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 18,
                                "cloud": 11,
                                "feelslike_c": 25.4,
                                "feelslike_f": 77.7,
                                "windchill_c": 27.3,
                                "windchill_f": 81.1,
                                "heatindex_c": 25.4,
                                "heatindex_f": 77.7,
                                "dewpoint_c": 0.8,
                                "dewpoint_f": 33.4,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 2.9,
                                "gust_kph": 4.7,
                                "uv": 7.0
                            },
                            {
                                "time_epoch": 1690428600,
                                "time": "2023-07-27 07:00",
                                "temp_c": 29.2,
                                "temp_f": 84.6,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 1.1,
                                "wind_kph": 1.8,
                                "wind_degree": 248,
                                "wind_dir": "WSW",
                                "pressure_mb": 1006.0,
                                "pressure_in": 29.72,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 15,
                                "cloud": 9,
                                "feelslike_c": 27.1,
                                "feelslike_f": 80.8,
                                "windchill_c": 29.2,
                                "windchill_f": 84.6,
                                "heatindex_c": 27.1,
                                "heatindex_f": 80.8,
                                "dewpoint_c": 0.0,
                                "dewpoint_f": 32.0,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 1.3,
                                "gust_kph": 2.2,
                                "uv": 7.0
                            },
                            {
                                "time_epoch": 1690432200,
                                "time": "2023-07-27 08:00",
                                "temp_c": 31.0,
                                "temp_f": 87.8,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 1.8,
                                "wind_kph": 2.9,
                                "wind_degree": 156,
                                "wind_dir": "SSE",
                                "pressure_mb": 1006.0,
                                "pressure_in": 29.7,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 14,
                                "cloud": 5,
                                "feelslike_c": 28.8,
                                "feelslike_f": 83.8,
                                "windchill_c": 31.0,
                                "windchill_f": 87.8,
                                "heatindex_c": 28.8,
                                "heatindex_f": 83.8,
                                "dewpoint_c": 0.2,
                                "dewpoint_f": 32.4,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 2.0,
                                "gust_kph": 3.2,
                                "uv": 8.0
                            },
                            {
                                "time_epoch": 1690435800,
                                "time": "2023-07-27 09:00",
                                "temp_c": 32.7,
                                "temp_f": 90.9,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 2.5,
                                "wind_kph": 4.0,
                                "wind_degree": 136,
                                "wind_dir": "SE",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.69,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 13,
                                "cloud": 3,
                                "feelslike_c": 30.5,
                                "feelslike_f": 86.9,
                                "windchill_c": 32.7,
                                "windchill_f": 90.9,
                                "heatindex_c": 30.5,
                                "heatindex_f": 86.9,
                                "dewpoint_c": 0.4,
                                "dewpoint_f": 32.7,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 2.9,
                                "gust_kph": 4.7,
                                "uv": 8.0
                            },
                            {
                                "time_epoch": 1690439400,
                                "time": "2023-07-27 10:00",
                                "temp_c": 34.4,
                                "temp_f": 93.9,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 3.1,
                                "wind_kph": 5.0,
                                "wind_degree": 130,
                                "wind_dir": "SE",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.66,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 12,
                                "cloud": 3,
                                "feelslike_c": 32.5,
                                "feelslike_f": 90.5,
                                "windchill_c": 34.4,
                                "windchill_f": 93.9,
                                "heatindex_c": 32.5,
                                "heatindex_f": 90.5,
                                "dewpoint_c": 0.7,
                                "dewpoint_f": 33.3,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 3.6,
                                "gust_kph": 5.8,
                                "uv": 8.0
                            },
                            {
                                "time_epoch": 1690443000,
                                "time": "2023-07-27 11:00",
                                "temp_c": 38.9,
                                "temp_f": 102.0,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 4.0,
                                "wind_kph": 6.5,
                                "wind_degree": 142,
                                "wind_dir": "SE",
                                "pressure_mb": 1004.0,
                                "pressure_in": 29.64,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 11,
                                "cloud": 3,
                                "feelslike_c": 38.3,
                                "feelslike_f": 100.9,
                                "windchill_c": 38.9,
                                "windchill_f": 102.0,
                                "heatindex_c": 38.3,
                                "heatindex_f": 100.9,
                                "dewpoint_c": 3.5,
                                "dewpoint_f": 38.3,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 4.7,
                                "gust_kph": 7.6,
                                "uv": 9.0
                            },
                            {
                                "time_epoch": 1690446600,
                                "time": "2023-07-27 12:00",
                                "temp_c": 40.1,
                                "temp_f": 104.2,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 4.5,
                                "wind_kph": 7.2,
                                "wind_degree": 178,
                                "wind_dir": "S",
                                "pressure_mb": 1003.0,
                                "pressure_in": 29.61,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 11,
                                "cloud": 4,
                                "feelslike_c": 40.1,
                                "feelslike_f": 104.2,
                                "windchill_c": 40.1,
                                "windchill_f": 104.2,
                                "heatindex_c": 40.1,
                                "heatindex_f": 104.2,
                                "dewpoint_c": 3.5,
                                "dewpoint_f": 38.3,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 5.1,
                                "gust_kph": 8.3,
                                "uv": 10.0
                            },
                            {
                                "time_epoch": 1690450200,
                                "time": "2023-07-27 13:00",
                                "temp_c": 39.8,
                                "temp_f": 103.6,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 10.7,
                                "wind_kph": 17.3,
                                "wind_degree": 240,
                                "wind_dir": "WSW",
                                "pressure_mb": 1002.0,
                                "pressure_in": 29.59,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 10,
                                "cloud": 6,
                                "feelslike_c": 39.6,
                                "feelslike_f": 103.3,
                                "windchill_c": 39.8,
                                "windchill_f": 103.6,
                                "heatindex_c": 39.6,
                                "heatindex_f": 103.3,
                                "dewpoint_c": 2.4,
                                "dewpoint_f": 36.3,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 12.3,
                                "gust_kph": 19.8,
                                "uv": 9.0
                            },
                            {
                                "time_epoch": 1690453800,
                                "time": "2023-07-27 14:00",
                                "temp_c": 40.9,
                                "temp_f": 105.6,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 19.7,
                                "wind_kph": 31.7,
                                "wind_degree": 254,
                                "wind_dir": "WSW",
                                "pressure_mb": 1002.0,
                                "pressure_in": 29.59,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 9,
                                "cloud": 6,
                                "feelslike_c": 41.3,
                                "feelslike_f": 106.3,
                                "windchill_c": 40.9,
                                "windchill_f": 105.6,
                                "heatindex_c": 41.3,
                                "heatindex_f": 106.3,
                                "dewpoint_c": 2.4,
                                "dewpoint_f": 36.3,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 22.6,
                                "gust_kph": 36.4,
                                "uv": 10.0
                            },
                            {
                                "time_epoch": 1690457400,
                                "time": "2023-07-27 15:00",
                                "temp_c": 40.1,
                                "temp_f": 104.2,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 21.5,
                                "wind_kph": 34.6,
                                "wind_degree": 267,
                                "wind_dir": "W",
                                "pressure_mb": 1002.0,
                                "pressure_in": 29.59,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 9,
                                "cloud": 3,
                                "feelslike_c": 40.1,
                                "feelslike_f": 104.2,
                                "windchill_c": 40.1,
                                "windchill_f": 104.2,
                                "heatindex_c": 40.1,
                                "heatindex_f": 104.2,
                                "dewpoint_c": 1.0,
                                "dewpoint_f": 33.8,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 24.6,
                                "gust_kph": 39.6,
                                "uv": 10.0
                            },
                            {
                                "time_epoch": 1690461000,
                                "time": "2023-07-27 16:00",
                                "temp_c": 38.9,
                                "temp_f": 102.0,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 21.7,
                                "wind_kph": 34.9,
                                "wind_degree": 275,
                                "wind_dir": "W",
                                "pressure_mb": 1002.0,
                                "pressure_in": 29.6,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 9,
                                "cloud": 0,
                                "feelslike_c": 38.3,
                                "feelslike_f": 100.9,
                                "windchill_c": 38.9,
                                "windchill_f": 102.0,
                                "heatindex_c": 38.3,
                                "heatindex_f": 100.9,
                                "dewpoint_c": 0.7,
                                "dewpoint_f": 33.3,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 25.1,
                                "gust_kph": 40.3,
                                "uv": 9.0
                            },
                            {
                                "time_epoch": 1690464600,
                                "time": "2023-07-27 17:00",
                                "temp_c": 37.4,
                                "temp_f": 99.3,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 19.0,
                                "wind_kph": 30.6,
                                "wind_degree": 277,
                                "wind_dir": "W",
                                "pressure_mb": 1003.0,
                                "pressure_in": 29.61,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 10,
                                "cloud": 0,
                                "feelslike_c": 36.2,
                                "feelslike_f": 97.2,
                                "windchill_c": 37.4,
                                "windchill_f": 99.3,
                                "heatindex_c": 36.2,
                                "heatindex_f": 97.2,
                                "dewpoint_c": 0.5,
                                "dewpoint_f": 32.9,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 21.9,
                                "gust_kph": 35.3,
                                "uv": 9.0
                            },
                            {
                                "time_epoch": 1690468200,
                                "time": "2023-07-27 18:00",
                                "temp_c": 33.0,
                                "temp_f": 91.4,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 13.2,
                                "wind_kph": 21.2,
                                "wind_degree": 277,
                                "wind_dir": "W",
                                "pressure_mb": 1004.0,
                                "pressure_in": 29.63,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 11,
                                "cloud": 2,
                                "feelslike_c": 30.9,
                                "feelslike_f": 87.6,
                                "windchill_c": 33.0,
                                "windchill_f": 91.4,
                                "heatindex_c": 30.9,
                                "heatindex_f": 87.6,
                                "dewpoint_c": -1.4,
                                "dewpoint_f": 29.5,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 15.2,
                                "gust_kph": 24.5,
                                "uv": 8.0
                            },
                            {
                                "time_epoch": 1690471800,
                                "time": "2023-07-27 19:00",
                                "temp_c": 31.7,
                                "temp_f": 89.1,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 8.3,
                                "wind_kph": 13.3,
                                "wind_degree": 268,
                                "wind_dir": "W",
                                "pressure_mb": 1004.0,
                                "pressure_in": 29.66,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 13,
                                "cloud": 3,
                                "feelslike_c": 29.5,
                                "feelslike_f": 85.1,
                                "windchill_c": 31.7,
                                "windchill_f": 89.1,
                                "heatindex_c": 29.5,
                                "heatindex_f": 85.1,
                                "dewpoint_c": -0.5,
                                "dewpoint_f": 31.1,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 9.6,
                                "gust_kph": 15.5,
                                "uv": 8.0
                            },
                            {
                                "time_epoch": 1690475400,
                                "time": "2023-07-27 20:00",
                                "temp_c": 29.7,
                                "temp_f": 85.5,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 6.5,
                                "wind_kph": 10.4,
                                "wind_degree": 264,
                                "wind_dir": "W",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.67,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 14,
                                "cloud": 5,
                                "feelslike_c": 27.5,
                                "feelslike_f": 81.5,
                                "windchill_c": 29.7,
                                "windchill_f": 85.5,
                                "heatindex_c": 27.5,
                                "heatindex_f": 81.5,
                                "dewpoint_c": -0.7,
                                "dewpoint_f": 30.7,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 8.5,
                                "gust_kph": 13.7,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690479000,
                                "time": "2023-07-27 21:00",
                                "temp_c": 28.1,
                                "temp_f": 82.6,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 6.0,
                                "wind_kph": 9.7,
                                "wind_degree": 267,
                                "wind_dir": "W",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.69,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 15,
                                "cloud": 8,
                                "feelslike_c": 26.1,
                                "feelslike_f": 79.0,
                                "windchill_c": 28.1,
                                "windchill_f": 82.6,
                                "heatindex_c": 26.1,
                                "heatindex_f": 79.0,
                                "dewpoint_c": -0.7,
                                "dewpoint_f": 30.7,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 9.4,
                                "gust_kph": 15.1,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690482600,
                                "time": "2023-07-27 22:00",
                                "temp_c": 26.4,
                                "temp_f": 79.5,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 6.0,
                                "wind_kph": 9.7,
                                "wind_degree": 270,
                                "wind_dir": "W",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.69,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 17,
                                "cloud": 8,
                                "feelslike_c": 24.8,
                                "feelslike_f": 76.6,
                                "windchill_c": 26.4,
                                "windchill_f": 79.5,
                                "heatindex_c": 24.8,
                                "heatindex_f": 76.6,
                                "dewpoint_c": -0.9,
                                "dewpoint_f": 30.4,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 11.2,
                                "gust_kph": 18.0,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690486200,
                                "time": "2023-07-27 23:00",
                                "temp_c": 25.0,
                                "temp_f": 77.0,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 6.7,
                                "wind_kph": 10.8,
                                "wind_degree": 281,
                                "wind_dir": "WNW",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.69,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 17,
                                "cloud": 9,
                                "feelslike_c": 23.8,
                                "feelslike_f": 74.8,
                                "windchill_c": 25.0,
                                "windchill_f": 77.0,
                                "heatindex_c": 23.8,
                                "heatindex_f": 74.8,
                                "dewpoint_c": -1.5,
                                "dewpoint_f": 29.3,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 14.1,
                                "gust_kph": 22.7,
                                "uv": 1.0
                            }
                        ]
                    }
                ]
            }
        }
    }),

    getters: {
        getCurrentData: (state) => state.current,
        getForecastData: (state) => state.forecast
    },

    actions: {

        setCurrentData(payload: any){
            try {
                this.current = payload
            } catch (error) {
                console.log(error);
            }
        },
        setForecastData(payload: any){
            try {
                this.forecast = payload
            } catch (error) {
                console.log(error);
            }
        }
    },
    
    persist: true
})
