import { defineStore } from "pinia";

export const useStore = defineStore('Store', {
    state: () => ({
        current : {
            "location": {
                "name": "Shiraz",
                "region": "Fars",
                "country": "Iran",
                "lat": 29.6,
                "lon": 52.54,
                "tz_id": "Asia/Tehran",
                "localtime_epoch": 1690488732,
                "localtime": "2023-07-27 23:42"
            },
            "current": {
                "last_updated_epoch": 1690488000,
                "last_updated": "2023-07-27 23:30",
                "temp_c": 30.0,
                "temp_f": 86.0,
                "is_day": 0,
                "condition": {
                    "text": "Clear",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                },
                "wind_mph": 6.9,
                "wind_kph": 11.2,
                "wind_degree": 310,
                "wind_dir": "NW",
                "pressure_mb": 1012.0,
                "pressure_in": 29.88,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 22,
                "cloud": 0,
                "feelslike_c": 27.8,
                "feelslike_f": 82.0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "uv": 1.0,
                "gust_mph": 14.1,
                "gust_kph": 22.7,
                "air_quality": {
                    "co": 212.0,
                    "no2": 1.899999976158142,
                    "o3": 154.5,
                    "so2": 3.5,
                    "pm2_5": 19.899999618530273,
                    "pm10": 45.5,
                    "us-epa-index": 2,
                    "gb-defra-index": 2
                }
            }
        },
        forecast : {
            "location": {
                "name": "Shiraz",
                "region": "Fars",
                "country": "Iran",
                "lat": 29.6,
                "lon": 52.54,
                "tz_id": "Asia/Tehran",
                "localtime_epoch": 1690489976,
                "localtime": "2023-07-28 0:02"
            },
            "current": {
                "last_updated_epoch": 1690489800,
                "last_updated": "2023-07-28 00:00",
                "temp_c": 30.0,
                "temp_f": 86.0,
                "is_day": 0,
                "condition": {
                    "text": "Clear",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                },
                "wind_mph": 6.9,
                "wind_kph": 11.2,
                "wind_degree": 300,
                "wind_dir": "WNW",
                "pressure_mb": 1012.0,
                "pressure_in": 29.88,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "humidity": 22,
                "cloud": 0,
                "feelslike_c": 27.8,
                "feelslike_f": 82.0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "uv": 1.0,
                "gust_mph": 9.8,
                "gust_kph": 15.8,
                "air_quality": {
                    "co": 217.0,
                    "no2": 1.7999999523162842,
                    "o3": 150.1999969482422,
                    "so2": 4.199999809265137,
                    "pm2_5": 21.600000381469727,
                    "pm10": 46.900001525878906,
                    "us-epa-index": 2,
                    "gb-defra-index": 2
                }
            },
            "forecast": {
                "forecastday": [
                    {
                        "date": "2023-07-28",
                        "date_epoch": 1690502400,
                        "day": {
                            "maxtemp_c": 40.1,
                            "maxtemp_f": 104.2,
                            "mintemp_c": 21.6,
                            "mintemp_f": 70.9,
                            "avgtemp_c": 30.7,
                            "avgtemp_f": 87.3,
                            "maxwind_mph": 15.0,
                            "maxwind_kph": 24.1,
                            "totalprecip_mm": 0.0,
                            "totalprecip_in": 0.0,
                            "totalsnow_cm": 0.0,
                            "avgvis_km": 10.0,
                            "avgvis_miles": 6.0,
                            "avghumidity": 14.0,
                            "daily_will_it_rain": 0,
                            "daily_chance_of_rain": 0,
                            "daily_will_it_snow": 0,
                            "daily_chance_of_snow": 0,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "uv": 8.0
                        },
                        "astro": {
                            "sunrise": "06:17 AM",
                            "sunset": "07:56 PM",
                            "moonrise": "03:52 PM",
                            "moonset": "01:26 AM",
                            "moon_phase": "Waxing Gibbous",
                            "moon_illumination": "71",
                            "is_moon_up": 0,
                            "is_sun_up": 0
                        },
                        "hour": [
                            {
                                "time_epoch": 1690489800,
                                "time": "2023-07-28 00:00",
                                "temp_c": 24.1,
                                "temp_f": 75.4,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 6.3,
                                "wind_kph": 10.1,
                                "wind_degree": 285,
                                "wind_dir": "WNW",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.68,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 18,
                                "cloud": 10,
                                "feelslike_c": 23.2,
                                "feelslike_f": 73.8,
                                "windchill_c": 24.1,
                                "windchill_f": 75.4,
                                "heatindex_c": 23.2,
                                "heatindex_f": 73.8,
                                "dewpoint_c": -1.6,
                                "dewpoint_f": 29.1,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 13.2,
                                "gust_kph": 21.2,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690493400,
                                "time": "2023-07-28 01:00",
                                "temp_c": 24.9,
                                "temp_f": 76.8,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 5.1,
                                "wind_kph": 8.3,
                                "wind_degree": 279,
                                "wind_dir": "W",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.68,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 19,
                                "cloud": 10,
                                "feelslike_c": 23.7,
                                "feelslike_f": 74.7,
                                "windchill_c": 24.9,
                                "windchill_f": 76.8,
                                "heatindex_c": 23.7,
                                "heatindex_f": 74.7,
                                "dewpoint_c": -0.5,
                                "dewpoint_f": 31.1,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 9.8,
                                "gust_kph": 15.8,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690497000,
                                "time": "2023-07-28 02:00",
                                "temp_c": 24.1,
                                "temp_f": 75.4,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 4.5,
                                "wind_kph": 7.2,
                                "wind_degree": 277,
                                "wind_dir": "W",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.67,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 19,
                                "cloud": 9,
                                "feelslike_c": 23.2,
                                "feelslike_f": 73.8,
                                "windchill_c": 24.1,
                                "windchill_f": 75.4,
                                "heatindex_c": 23.2,
                                "heatindex_f": 73.8,
                                "dewpoint_c": -0.9,
                                "dewpoint_f": 30.4,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 9.2,
                                "gust_kph": 14.8,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690500600,
                                "time": "2023-07-28 03:00",
                                "temp_c": 22.9,
                                "temp_f": 73.2,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 4.7,
                                "wind_kph": 7.6,
                                "wind_degree": 291,
                                "wind_dir": "WNW",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.69,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 19,
                                "cloud": 9,
                                "feelslike_c": 22.5,
                                "feelslike_f": 72.5,
                                "windchill_c": 22.9,
                                "windchill_f": 73.2,
                                "heatindex_c": 22.5,
                                "heatindex_f": 72.5,
                                "dewpoint_c": -2.0,
                                "dewpoint_f": 28.4,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 9.8,
                                "gust_kph": 15.8,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690504200,
                                "time": "2023-07-28 04:00",
                                "temp_c": 22.1,
                                "temp_f": 71.8,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 4.0,
                                "wind_kph": 6.5,
                                "wind_degree": 282,
                                "wind_dir": "WNW",
                                "pressure_mb": 1006.0,
                                "pressure_in": 29.7,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 19,
                                "cloud": 9,
                                "feelslike_c": 22.1,
                                "feelslike_f": 71.8,
                                "windchill_c": 22.1,
                                "windchill_f": 71.8,
                                "heatindex_c": 22.1,
                                "heatindex_f": 71.8,
                                "dewpoint_c": -2.3,
                                "dewpoint_f": 27.9,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 8.5,
                                "gust_kph": 13.7,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690507800,
                                "time": "2023-07-28 05:00",
                                "temp_c": 21.9,
                                "temp_f": 71.4,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 2.5,
                                "wind_kph": 4.0,
                                "wind_degree": 273,
                                "wind_dir": "W",
                                "pressure_mb": 1006.0,
                                "pressure_in": 29.71,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 21,
                                "cloud": 7,
                                "feelslike_c": 21.9,
                                "feelslike_f": 71.4,
                                "windchill_c": 21.9,
                                "windchill_f": 71.4,
                                "heatindex_c": 22.1,
                                "heatindex_f": 71.8,
                                "dewpoint_c": -1.4,
                                "dewpoint_f": 29.5,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 5.1,
                                "gust_kph": 8.3,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690511400,
                                "time": "2023-07-28 06:00",
                                "temp_c": 26.3,
                                "temp_f": 79.3,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 2.0,
                                "wind_kph": 3.2,
                                "wind_degree": 269,
                                "wind_dir": "W",
                                "pressure_mb": 1006.0,
                                "pressure_in": 29.72,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 18,
                                "cloud": 6,
                                "feelslike_c": 24.7,
                                "feelslike_f": 76.5,
                                "windchill_c": 26.3,
                                "windchill_f": 79.3,
                                "heatindex_c": 24.7,
                                "heatindex_f": 76.5,
                                "dewpoint_c": 0.2,
                                "dewpoint_f": 32.4,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 2.7,
                                "gust_kph": 4.3,
                                "uv": 7.0
                            },
                            {
                                "time_epoch": 1690515000,
                                "time": "2023-07-28 07:00",
                                "temp_c": 28.2,
                                "temp_f": 82.8,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 0.9,
                                "wind_kph": 1.4,
                                "wind_degree": 217,
                                "wind_dir": "SW",
                                "pressure_mb": 1006.0,
                                "pressure_in": 29.72,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 15,
                                "cloud": 6,
                                "feelslike_c": 26.2,
                                "feelslike_f": 79.2,
                                "windchill_c": 28.2,
                                "windchill_f": 82.8,
                                "heatindex_c": 26.2,
                                "heatindex_f": 79.2,
                                "dewpoint_c": -1.2,
                                "dewpoint_f": 29.8,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 1.1,
                                "gust_kph": 1.8,
                                "uv": 7.0
                            },
                            {
                                "time_epoch": 1690518600,
                                "time": "2023-07-28 08:00",
                                "temp_c": 29.9,
                                "temp_f": 85.8,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 2.0,
                                "wind_kph": 3.2,
                                "wind_degree": 158,
                                "wind_dir": "SSE",
                                "pressure_mb": 1006.0,
                                "pressure_in": 29.71,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 13,
                                "cloud": 5,
                                "feelslike_c": 27.7,
                                "feelslike_f": 81.9,
                                "windchill_c": 29.9,
                                "windchill_f": 85.8,
                                "heatindex_c": 27.7,
                                "heatindex_f": 81.9,
                                "dewpoint_c": -1.2,
                                "dewpoint_f": 29.8,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 2.2,
                                "gust_kph": 3.6,
                                "uv": 7.0
                            },
                            {
                                "time_epoch": 1690522200,
                                "time": "2023-07-28 09:00",
                                "temp_c": 31.7,
                                "temp_f": 89.1,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 2.9,
                                "wind_kph": 4.7,
                                "wind_degree": 148,
                                "wind_dir": "SSE",
                                "pressure_mb": 1006.0,
                                "pressure_in": 29.7,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 12,
                                "cloud": 4,
                                "feelslike_c": 29.5,
                                "feelslike_f": 85.1,
                                "windchill_c": 31.7,
                                "windchill_f": 89.1,
                                "heatindex_c": 29.5,
                                "heatindex_f": 85.1,
                                "dewpoint_c": -1.2,
                                "dewpoint_f": 29.8,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 3.4,
                                "gust_kph": 5.4,
                                "uv": 8.0
                            },
                            {
                                "time_epoch": 1690525800,
                                "time": "2023-07-28 10:00",
                                "temp_c": 33.4,
                                "temp_f": 92.1,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 2.9,
                                "wind_kph": 4.7,
                                "wind_degree": 161,
                                "wind_dir": "SSE",
                                "pressure_mb": 1005.0,
                                "pressure_in": 29.67,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 10,
                                "cloud": 3,
                                "feelslike_c": 31.3,
                                "feelslike_f": 88.3,
                                "windchill_c": 33.4,
                                "windchill_f": 92.1,
                                "heatindex_c": 31.3,
                                "heatindex_f": 88.3,
                                "dewpoint_c": -1.7,
                                "dewpoint_f": 28.9,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 3.4,
                                "gust_kph": 5.4,
                                "uv": 8.0
                            },
                            {
                                "time_epoch": 1690529400,
                                "time": "2023-07-28 11:00",
                                "temp_c": 37.8,
                                "temp_f": 100.0,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 3.4,
                                "wind_kph": 5.4,
                                "wind_degree": 169,
                                "wind_dir": "S",
                                "pressure_mb": 1004.0,
                                "pressure_in": 29.64,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 9,
                                "cloud": 3,
                                "feelslike_c": 36.8,
                                "feelslike_f": 98.2,
                                "windchill_c": 37.8,
                                "windchill_f": 100.0,
                                "heatindex_c": 36.8,
                                "heatindex_f": 98.2,
                                "dewpoint_c": -0.4,
                                "dewpoint_f": 31.3,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 3.8,
                                "gust_kph": 6.1,
                                "uv": 9.0
                            },
                            {
                                "time_epoch": 1690533000,
                                "time": "2023-07-28 12:00",
                                "temp_c": 39.2,
                                "temp_f": 102.6,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 4.3,
                                "wind_kph": 6.8,
                                "wind_degree": 207,
                                "wind_dir": "SSW",
                                "pressure_mb": 1003.0,
                                "pressure_in": 29.6,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 8,
                                "cloud": 4,
                                "feelslike_c": 38.8,
                                "feelslike_f": 101.8,
                                "windchill_c": 39.2,
                                "windchill_f": 102.6,
                                "heatindex_c": 38.8,
                                "heatindex_f": 101.8,
                                "dewpoint_c": -1.0,
                                "dewpoint_f": 30.2,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 4.9,
                                "gust_kph": 7.9,
                                "uv": 9.0
                            },
                            {
                                "time_epoch": 1690536600,
                                "time": "2023-07-28 13:00",
                                "temp_c": 39.9,
                                "temp_f": 103.8,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 8.9,
                                "wind_kph": 14.4,
                                "wind_degree": 236,
                                "wind_dir": "WSW",
                                "pressure_mb": 1001.0,
                                "pressure_in": 29.57,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 8,
                                "cloud": 5,
                                "feelslike_c": 39.8,
                                "feelslike_f": 103.6,
                                "windchill_c": 39.9,
                                "windchill_f": 103.8,
                                "heatindex_c": 39.8,
                                "heatindex_f": 103.6,
                                "dewpoint_c": -1.3,
                                "dewpoint_f": 29.7,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 10.3,
                                "gust_kph": 16.6,
                                "uv": 9.0
                            },
                            {
                                "time_epoch": 1690540200,
                                "time": "2023-07-28 14:00",
                                "temp_c": 40.4,
                                "temp_f": 104.7,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 15.0,
                                "wind_kph": 24.1,
                                "wind_degree": 249,
                                "wind_dir": "WSW",
                                "pressure_mb": 1001.0,
                                "pressure_in": 29.56,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 8,
                                "cloud": 5,
                                "feelslike_c": 40.5,
                                "feelslike_f": 104.9,
                                "windchill_c": 40.4,
                                "windchill_f": 104.7,
                                "heatindex_c": 40.5,
                                "heatindex_f": 104.9,
                                "dewpoint_c": -0.7,
                                "dewpoint_f": 30.7,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 17.2,
                                "gust_kph": 27.7,
                                "uv": 10.0
                            },
                            {
                                "time_epoch": 1690543800,
                                "time": "2023-07-28 15:00",
                                "temp_c": 39.9,
                                "temp_f": 103.8,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 15.7,
                                "wind_kph": 25.2,
                                "wind_degree": 251,
                                "wind_dir": "WSW",
                                "pressure_mb": 1001.0,
                                "pressure_in": 29.54,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 8,
                                "cloud": 3,
                                "feelslike_c": 39.8,
                                "feelslike_f": 103.6,
                                "windchill_c": 39.9,
                                "windchill_f": 103.8,
                                "heatindex_c": 39.8,
                                "heatindex_f": 103.6,
                                "dewpoint_c": -0.6,
                                "dewpoint_f": 30.9,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 18.1,
                                "gust_kph": 29.2,
                                "uv": 9.0
                            },
                            {
                                "time_epoch": 1690547400,
                                "time": "2023-07-28 16:00",
                                "temp_c": 39.2,
                                "temp_f": 102.6,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 15.7,
                                "wind_kph": 25.2,
                                "wind_degree": 260,
                                "wind_dir": "W",
                                "pressure_mb": 1000.0,
                                "pressure_in": 29.54,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 9,
                                "cloud": 0,
                                "feelslike_c": 38.8,
                                "feelslike_f": 101.8,
                                "windchill_c": 39.2,
                                "windchill_f": 102.6,
                                "heatindex_c": 38.8,
                                "heatindex_f": 101.8,
                                "dewpoint_c": -0.2,
                                "dewpoint_f": 31.6,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 18.1,
                                "gust_kph": 29.2,
                                "uv": 9.0
                            },
                            {
                                "time_epoch": 1690551000,
                                "time": "2023-07-28 17:00",
                                "temp_c": 35.0,
                                "temp_f": 95.0,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 13.6,
                                "wind_kph": 22.0,
                                "wind_degree": 269,
                                "wind_dir": "W",
                                "pressure_mb": 1001.0,
                                "pressure_in": 29.55,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 10,
                                "cloud": 0,
                                "feelslike_c": 33.2,
                                "feelslike_f": 91.8,
                                "windchill_c": 35.0,
                                "windchill_f": 95.0,
                                "heatindex_c": 33.2,
                                "heatindex_f": 91.8,
                                "dewpoint_c": -1.6,
                                "dewpoint_f": 29.1,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 15.7,
                                "gust_kph": 25.2,
                                "uv": 9.0
                            },
                            {
                                "time_epoch": 1690554600,
                                "time": "2023-07-28 18:00",
                                "temp_c": 33.6,
                                "temp_f": 92.5,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 9.4,
                                "wind_kph": 15.1,
                                "wind_degree": 273,
                                "wind_dir": "W",
                                "pressure_mb": 1001.0,
                                "pressure_in": 29.57,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 12,
                                "cloud": 0,
                                "feelslike_c": 31.5,
                                "feelslike_f": 88.7,
                                "windchill_c": 33.6,
                                "windchill_f": 92.5,
                                "heatindex_c": 31.5,
                                "heatindex_f": 88.7,
                                "dewpoint_c": 0.2,
                                "dewpoint_f": 32.4,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 10.7,
                                "gust_kph": 17.3,
                                "uv": 8.0
                            },
                            {
                                "time_epoch": 1690558200,
                                "time": "2023-07-28 19:00",
                                "temp_c": 31.9,
                                "temp_f": 89.4,
                                "is_day": 1,
                                "condition": {
                                    "text": "Sunny",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 7.6,
                                "wind_kph": 12.2,
                                "wind_degree": 267,
                                "wind_dir": "W",
                                "pressure_mb": 1002.0,
                                "pressure_in": 29.6,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 15,
                                "cloud": 0,
                                "feelslike_c": 29.7,
                                "feelslike_f": 85.5,
                                "windchill_c": 31.9,
                                "windchill_f": 89.4,
                                "heatindex_c": 29.7,
                                "heatindex_f": 85.5,
                                "dewpoint_c": 1.8,
                                "dewpoint_f": 35.2,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 8.7,
                                "gust_kph": 14.0,
                                "uv": 8.0
                            },
                            {
                                "time_epoch": 1690561800,
                                "time": "2023-07-28 20:00",
                                "temp_c": 29.8,
                                "temp_f": 85.6,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 6.5,
                                "wind_kph": 10.4,
                                "wind_degree": 263,
                                "wind_dir": "W",
                                "pressure_mb": 1003.0,
                                "pressure_in": 29.62,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 17,
                                "cloud": 0,
                                "feelslike_c": 27.6,
                                "feelslike_f": 81.7,
                                "windchill_c": 29.8,
                                "windchill_f": 85.6,
                                "heatindex_c": 27.6,
                                "heatindex_f": 81.7,
                                "dewpoint_c": 2.5,
                                "dewpoint_f": 36.5,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 9.2,
                                "gust_kph": 14.8,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690565400,
                                "time": "2023-07-28 21:00",
                                "temp_c": 28.7,
                                "temp_f": 83.7,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 6.0,
                                "wind_kph": 9.7,
                                "wind_degree": 264,
                                "wind_dir": "W",
                                "pressure_mb": 1003.0,
                                "pressure_in": 29.63,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 20,
                                "cloud": 4,
                                "feelslike_c": 26.6,
                                "feelslike_f": 79.9,
                                "windchill_c": 28.7,
                                "windchill_f": 83.7,
                                "heatindex_c": 26.6,
                                "heatindex_f": 79.9,
                                "dewpoint_c": 3.8,
                                "dewpoint_f": 38.8,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 8.7,
                                "gust_kph": 14.0,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690569000,
                                "time": "2023-07-28 22:00",
                                "temp_c": 27.1,
                                "temp_f": 80.8,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 6.3,
                                "wind_kph": 10.1,
                                "wind_degree": 269,
                                "wind_dir": "W",
                                "pressure_mb": 1004.0,
                                "pressure_in": 29.64,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 23,
                                "cloud": 6,
                                "feelslike_c": 25.6,
                                "feelslike_f": 78.1,
                                "windchill_c": 27.1,
                                "windchill_f": 80.8,
                                "heatindex_c": 25.6,
                                "heatindex_f": 78.1,
                                "dewpoint_c": 4.4,
                                "dewpoint_f": 39.9,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 10.3,
                                "gust_kph": 16.6,
                                "uv": 1.0
                            },
                            {
                                "time_epoch": 1690572600,
                                "time": "2023-07-28 23:00",
                                "temp_c": 26.0,
                                "temp_f": 78.8,
                                "is_day": 0,
                                "condition": {
                                    "text": "Clear",
                                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                    "code": 1000
                                },
                                "wind_mph": 5.6,
                                "wind_kph": 9.0,
                                "wind_degree": 272,
                                "wind_dir": "W",
                                "pressure_mb": 1004.0,
                                "pressure_in": 29.63,
                                "precip_mm": 0.0,
                                "precip_in": 0.0,
                                "humidity": 25,
                                "cloud": 4,
                                "feelslike_c": 25.0,
                                "feelslike_f": 77.0,
                                "windchill_c": 26.0,
                                "windchill_f": 78.8,
                                "heatindex_c": 25.0,
                                "heatindex_f": 77.0,
                                "dewpoint_c": 4.6,
                                "dewpoint_f": 40.3,
                                "will_it_rain": 0,
                                "chance_of_rain": 0,
                                "will_it_snow": 0,
                                "chance_of_snow": 0,
                                "vis_km": 10.0,
                                "vis_miles": 6.0,
                                "gust_mph": 10.1,
                                "gust_kph": 16.2,
                                "uv": 1.0
                            }
                        ]
                    }
                ]
            }
        }
    }),

    getters: {
        getCurrentData: (state) => state.current,
        getForecastData: (state) => state.forecast
    },

    actions: {

        setCurrentData(payload: any){
            try {
                this.current = payload
            } catch (error) {
                console.log(error);
            }
        },
        setForecastData(payload: any){
            try {
                this.forecast = payload
            } catch (error) {
                console.log(error);
            }
        }
    },
    
    persist: true
})
